src/Otus.Teaching.Pcf.Dictionary.MVCWebHost/Models/ErrorViewModel.cs
using System;

namespace Otus.Teaching.Pcf.Dictionary.MVCWebHost.Models
{
    public class ErrorViewModel
    {
        public string RequestId { get; set; }

        public bool ShowRequestId => !string.IsNullOrEmpty(RequestId);
    }
}

src/Otus.Teaching.Pcf.Dictionary.MVCWebHost/Controllers/HomeController.cs
using Microsoft.AspNetCore.Mvc;
using Microsoft.Extensions.Logging;
using Otus.Teaching.Pcf.Dictionary.MVCWebHost.Models;
using System;
using System.Collections.Generic;
using System.Diagnostics;
using System.Linq;
using System.Threading.Tasks;

namespace Otus.Teaching.Pcf.Dictionary.MVCWebHost.Controllers
{
    public class HomeController : Controller
    {
        private readonly ILogger<HomeController> _logger;

        public HomeController(ILogger<HomeController> logger)
        {
            _logger = logger;
        }

        public IActionResult Index()
        {
            return View();
        }

        public IActionResult Privacy()
        {
            return View();
        }

        [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
        public IActionResult Error()
        {
            return View(new ErrorViewModel { RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier });
        }
    }
}

src/Otus.Teaching.Pcf.Dictionary.MVCWebHost/Controllers/PreferenceController.cs
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Mvc;
using Microsoft.Extensions.Logging;
using Otus.Teaching.Pcf.Dictionary.Services.DTOs;
using Otus.Teaching.Pcf.Dictionary.Services.Interfaces;
using Otus.Teaching.Pcf.Dictionary.Services.Utils.Exceptions;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace Otus.Teaching.Pcf.Dictionary.MVCWebHost.Controllers
{
    public class PreferenceController : Controller
    {
        private readonly IPreferenceService _preferenceService;
        private readonly ILogger<HomeController> _logger;

        public PreferenceController(IPreferenceService preferenceService,
                                     ILogger<HomeController> logger)
        {
            _logger = logger;
            _preferenceService = preferenceService;
        }

        // GET: PreferenceController
        public async Task<ActionResult> Preferences()
        {
            var proferences = await _preferenceService.GetList();
            return View("Preferences", proferences);
        }

        public ActionResult PartialPreferenceList()
        {
            return PartialView("PartialPreferenceList", _preferenceService.GetList());
        }

        // GET: PreferenceController/Create
        public ActionResult Create()
        {
            return View();
        }

        // POST: PreferenceController/Create
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<ActionResult> Create([FromForm] PreferenceDTO dto)
        {
            try
            {
                await _preferenceService.Create(dto);
                return RedirectToAction("Preferences");
            }
            catch (Exception ex)
            {
                _logger.LogError(ex.Message);
                return View(dto);
            }
        }

        // GET: PreferenceController/Edit/5
        public async Task<ActionResult> Edit(Guid id)
        {
            var model = await _preferenceService.Get(id);
            return View(model);
        }

        // POST: PreferenceController/Edit/5
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<ActionResult> Edit([FromForm] PreferenceDTO dto)
        {
            try
            {
                await _preferenceService.Update(dto);
                return RedirectToAction("Preferences");
            }
            catch
            {
                return View(dto);
            }
        }

        // GET: PreferenceController/Delete/5
        public ActionResult Delete(int id)
        {
            return View();
        }

        // POST: PreferenceController/Delete/5
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<ActionResult> Delete([FromForm] PreferenceDTO dto)
        {
            try
            {
                await _preferenceService.Delete(dto);
                return RedirectToAction("Preferences");
            }
            catch (Exception ex)
            {
                _logger.LogError(ex.Message);
                return View(dto);
            }
        }
    }
}

src/Otus.Teaching.Pcf.Dictionary.MVCWebHost/Controllers/PromoCodeController.cs
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Mvc;
using Microsoft.Extensions.Logging;
using Otus.Teaching.Pcf.Dictionary.Services.DTOs;
using Otus.Teaching.Pcf.Dictionary.Services.Interfaces;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace Otus.Teaching.Pcf.Dictionary.MVCWebHost.Controllers
{
    public class PromoCodeController : Controller
    {
        private readonly IGetPromoCodeService _getPromoCodeService;
        private readonly ILogger<HomeController> _logger;

        public PromoCodeController(IGetPromoCodeService getPromoCodeService,
                                     ILogger<HomeController> logger)
        {
            _logger = logger;
            _getPromoCodeService = getPromoCodeService;
        }

        // GET: PreferenceController
        public async Task<ActionResult> PromoCodes()
        {
            var promoCodes = await _getPromoCodeService.GetList();
            return View("PromoCodes", promoCodes);
        }

    }
}

src/Otus.Teaching.Pcf.Dictionary.MVCWebHost/Views/Home/Index.cshtml
@{
    ViewData["Title"] = "Home Page";
}

<div class="text-center">
    <h1 class="display-4">Welcome</h1>
    <p>Learn about <a href="https://docs.microsoft.com/aspnet/core">building Web apps with ASP.NET Core</a>.</p>
</div>

src/Otus.Teaching.Pcf.Dictionary.MVCWebHost/Views/Preference/Create.cshtml
@model Otus.Teaching.Pcf.Dictionary.Services.DTOs.PreferenceDTO

@{
	ViewData["Title"] = "Создать";
}

<h1>Создать</h1>

<h4>Предпочтение</h4>
<hr />
<div class="row">
 <div class="col-md-4">
  <form asp-action="Create">
   <div asp-validation-summary="ModelOnly" class="text-danger"></div>
   <div class="form-group">
	<label asp-for="Name" class="control-label"></label>
	<input asp-for="Name" class="form-control" />
	<span asp-validation-for="Name" class="text-danger"></span>
   </div>
   <div class="form-group">
	<input type="submit" value="Создать" class="btn btn-primary" />
   </div>
  </form>
 </div>
</div>

<div>
 <a asp-action="Preferences">К списку</a>
</div>

@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}

src/Otus.Teaching.Pcf.Dictionary.MVCWebHost/Views/Preference/Edit.cshtml
@model Otus.Teaching.Pcf.Dictionary.Services.DTOs.PreferenceDTO

@{
	ViewData["Title"] = "Edit";
}

<h1>Редактирование</h1>

<h4>Предпочтение</h4>
<hr />
<div class="row">
 <div class="col-md-4">
  <form asp-action="Edit">
   <div asp-validation-summary="ModelOnly" class="text-danger"></div>
   <div class="form-group">
	<label asp-for="Name" class="control-label"></label>
	<input asp-for="Name" class="form-control" />
	<span asp-validation-for="Name" class="text-danger"></span>
	<input asp-for="Id" class="form-control" type="hidden" />
   </div>
   <div class="form-group">
	<input type="submit" value="Save" class="btn btn-primary" />
   </div>
  </form>
 </div>
</div>

<div>
 <a asp-action="Index">Back to List</a>
</div>

@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}

src/Otus.Teaching.Pcf.Dictionary.MVCWebHost/Views/Preference/Preferences.cshtml
@model IEnumerable<Otus.Teaching.Pcf.Dictionary.Services.DTOs.PreferenceDTO>

@{
	ViewData["Title"] = "Preferences";
}

<h1>Справочник предпочтений</h1>

<p>
 <a asp-action="Create">Создать новый</a>
</p>
<table class="table table-striped">
 <thead>
  <tr>
   <th>
				@Html.DisplayNameFor(model => model.Name)
   </th>
   <th>
				@Html.DisplayNameFor(model => model.Id)
   </th>
   <th></th>
  </tr>
 </thead>
 <tbody>
		@foreach (var item in Model)
		{
	  <tr>
	   <td>
					@Html.DisplayFor(modelItem => item.Name)
	   </td>
	   <td>
					@Html.DisplayFor(modelItem => item.Id)
	   </td>
	   <td>
					@Html.ActionLink("Изменить", "Edit", new {  id=item.Id  }) |
					@Html.ActionLink("Удалить", "Delete", new { id=item.Id  })
	   </td>
	  </tr>
		}
 </tbody>
</table>

src/Otus.Teaching.Pcf.Dictionary.MVCWebHost/Views/PromoCode/PromoCodes.cshtml
@model IEnumerable<Otus.Teaching.Pcf.Dictionary.Services.DTOs.PromoCodeDTOs.GetPromoCodeDTO>

@{
    ViewData["Title"] = "PromoCodes";
}

<h1>PromoCodes</h1>

<p>
    <a asp-action="Create">Create New</a>
</p>
<table class="table">
    <thead>
        <tr>
            <th>
                @Html.DisplayNameFor(model => model.Code)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.ServiceInfo)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.BeginDate)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.EndDate)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.PartnerName)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.PreferenceName)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Id)
            </th>
            <th></th>
        </tr>
    </thead>
    <tbody>
@foreach (var item in Model) {
        <tr>
            <td>
                @Html.DisplayFor(modelItem => item.Code)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.ServiceInfo)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.BeginDate)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.EndDate)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.PartnerName)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.PreferenceName)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Id)
            </td>
            <td>
                @Html.ActionLink("Edit", "Edit", new { /* id=item.PrimaryKey */ }) |
                @Html.ActionLink("Details", "Details", new { /* id=item.PrimaryKey */ }) |
                @Html.ActionLink("Delete", "Delete", new { /* id=item.PrimaryKey */ })
            </td>
        </tr>
}
    </tbody>
</table>

src/Otus.Teaching.Pcf.Dictionary.MVCWebHost/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
	<meta charset="utf-8" />
	<meta name="viewport" content="width=device-width, initial-scale=1.0" />
	<title>@ViewData["Title"] - Otus.Teaching.Pcf.Dictionary.MVCWebHost</title>
	<link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
	<link rel="stylesheet" href="~/css/site.css" />
</head>
<body>
	<header>
		<nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
			<div class="container">
				<a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">Otus.Teaching.Pcf.Dictionary.MVCWebHost</a>
				<button class="navbar-toggler" type="button" data-toggle="collapse" data-target=".navbar-collapse" aria-controls="navbarSupportedContent"
						aria-expanded="false" aria-label="Toggle navigation">
					<span class="navbar-toggler-icon"></span>
				</button>
				<div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
					<ul class="navbar-nav flex-grow-1">
						<li class="nav-item">
							<a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Index">Home</a>
						</li>
						<li class="nav-item">
							<a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
						</li>
						<li class="nav-item">
							<a class="nav-link text-dark" asp-area="" asp-controller="Preference" asp-action="Preferences">Предпочтения</a>
						</li>
						<li class="nav-item">
							<a class="nav-link text-dark" asp-area="" asp-controller="PromoCode" asp-action="PromoCodes">Промокоды</a>
						</li>
					</ul>
				</div>
			</div>
		</nav>
	</header>
	<div class="container">
		<main role="main" class="pb-3">
			@RenderBody()
		</main>
	</div>

	<footer class="border-top footer text-muted">
		<div class="container">
			&copy; 2021 - Otus.Teaching.Pcf.Dictionary.MVCWebHost - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
		</div>
	</footer>
	<script src="~/lib/jquery/dist/jquery.min.js"></script>
	<script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
	<script src="~/js/site.js" asp-append-version="true"></script>
	@await RenderSectionAsync("Scripts", required: false)
</body>
</html>